// Components
import Layout from '../components/Layout';

const Index = () => {
    return (
      <Layout>
          <h1 className="text-2xl font-semibold">Scroll me!</h1>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>
              Hi
          </p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
          <p>Hi</p>
      </Layout>
    )
}

export default Index;
